apiVersion: batch/v1
kind: Job
metadata:
  name: fybrik-job
  namespace: fybrik-workload
spec:
  template:
    spec:
      containers:
      - name: fybrik-job
        image: ghcr.io/fybrik/fybrik-workload-job:0.0.0
        imagePullPolicy: Always
        command: ["python3", "job.py"]
        args:
        - fybrik-airbyte-sample/paysim-csv
        - fybrik-airbyte-sample/userdata
      restartPolicy: Never
