kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fybrikapplications
  namespace: fybrik-workload
rules:
- apiGroups: ["app.fybrik.io"]
  resources: ["fybrikapplications"]
  verbs: ["create", "get", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fybrikapplications
  namespace: fybrik-workload
subjects:
- kind: ServiceAccount
  name: default
  namespace: fybrik-workload
roleRef:
  kind: Role
  name: fybrikapplications
  apiGroup: rbac.authorization.k8s.io
